name: Docker Image CI

on: [push]

jobs:

  build:
 
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: |
        docker login -u ${{ secrets.DOCKERHUB_USER }} -p ${{ secrets.DOCKERHUB_TOKEN }}
        docker build . --file Dockerfile -t ilirbekteshi/argocd-github-status:$GITHUB_SHA -t ilirbekteshi/argocd-github-status:latest
        docker push ilirbekteshi/argocd-github-status:$GITHUB_SHA
        docker push ilirbekteshi/argocd-github-status:latest
